# Generated by Django 5.2.1 on 2025-06-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipogeneral',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='inventario.empleado'),
        ),
    ]
