# Generated by Django 5.2.1 on 2025-06-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipogeneral_empleado_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipogeneral',
            name='empleado_asignado',
        ),
        migrations.AddField(
            model_name='equipogeneral',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.empleado'),
        ),
    ]
