# Generated by Django 5.2.3 on 2025-06-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_equipogeneral_empleado_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('marca', models.CharField(choices=[('Aruba', 'Aruba'), ('Ubiquity', 'Ubiquity'), ('Ruckus', 'Ruckus')], max_length=20)),
                ('planta', models.CharField(choices=[('1', 'Planta 1'), ('2', 'Planta 2'), ('3', 'Planta 3'), ('4', 'Planta 4'), ('5', 'Planta 5'), ('6', 'Planta 6')], max_length=1)),
                ('lugar', models.CharField(choices=[('Plot1', 'Plot 1'), ('Plot2', 'Plot 2')], max_length=10)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
