# Generated by Django 5.2.3 on 2025-06-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='estado',
        ),
    ]
