# Generated by Django 5.2.3 on 2025-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_switch_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
