# Generated by Django 5.2.3 on 2025-07-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_switch_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
