# Generated by Django 5.2.3 on 2025-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_empleado_departamento_empleado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='delegacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
