# Generated by Django 5.2.3 on 2025-11-12 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_empleado_delegacion_empleado_rol_empleado_tipo_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(blank=True, choices=[('it_manager', 'IT Manager'), ('deputy_it_manager', 'Deputy IT Manager'), ('tecnico', 'Técnico'), ('av_manager', 'AV Manager'), ('otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_rol',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('estandar', 'Estándar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='delegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.delegacion'),
        ),
    ]
