# Generated by Django 5.2.3 on 2026-03-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_delegacion_empleado_user_alter_empleado_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegacion',
            options={'verbose_name_plural': 'Delegaciones'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='equipogeneral',
            options={'ordering': ['id_inventario'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='oraclepos',
            options={'verbose_name': 'Oracle POS', 'verbose_name_plural': 'Oracle POS'},
        ),
        migrations.AlterModelOptions(
            name='pda',
            options={'verbose_name': 'PDA', 'verbose_name_plural': 'PDAs'},
        ),
        migrations.AlterModelOptions(
            name='sim',
            options={'verbose_name': 'SIM', 'verbose_name_plural': 'SIMs'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['planta', 'nombre'], 'verbose_name_plural': 'Switches'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('solicitante', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes', to='inventario.empleado')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes', to='inventario.equipogeneral')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
