# Generated by Django 5.2.3 on 2026-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_delegacion_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='emisor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='emisor_rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='equipos_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='numero_parte',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='observaciones_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='receptor_departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='receptor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='receptor_rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='receptor_ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='parte',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
